# Generated by Django 4.2.1 on 2023-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
