# Generated by Django 4.2.1 on 2023-06-03 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_vehicle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
