# Generated by Django 4.2.1 on 2023-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_roomtype_remove_room_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default='l'),
            preserve_default=False,
        ),
    ]
